modules/dxp/apps/osb/osb-faro/osb-faro-provisioning-client/src/main/java/com/liferay/osb/faro/provisioning/client/model/OSBAccountEntry.java
Jira ticket: https://issues.liferay.com/browse/LRAC-14261
=> LRAC-14261 | release

modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/application/MainApplication.java, modules/dxp/apps/osb/osb-faro/wedeploy/dev/resources/rewrite.config, modules/dxp/apps/osb/osb-faro/wedeploy/prd/resources/rewrite.config, modules/dxp/apps/osb/osb-faro/wedeploy/uat/resources/rewrite.config
Jira ticket: https://issues.liferay.com/browse/LRAC-14223
=> LRAC-14223 | release

modules/dxp/apps/osb/osb-faro/osb-faro-engine-client/src/main/java/com/liferay/osb/faro/engine/client/model/LCPProject.java
https://liferay.atlassian.net/browse/LRAC-14747
=> LRAC-14747 | 4.2.x

modules/dxp/apps/osb/osb-faro/wedeploy/dev/Dockerfile, modules/dxp/apps/osb/osb-faro/wedeploy/prd/Dockerfile, modules/dxp/apps/osb/osb-faro/wedeploy/uat/Dockerfile
https://liferay.atlassian.net/browse/LRAC-14777
=> LRAC-14777 | 4.3.x

modules/dxp/apps/osb/osb-faro/osb-faro-admin-web/bnd.bnd, modules/dxp/apps/osb/osb-faro/osb-faro-admin-web/build.gradle, modules/dxp/apps/osb/osb-faro/osb-faro-api/bnd.bnd, modules/dxp/apps/osb/osb-faro/osb-faro-api/build.gradle, modules/dxp/apps/osb/osb-faro/osb-faro-contacts-api/bnd.bnd, modules/dxp/apps/osb/osb-faro/osb-faro-contacts-api/build.gradle, modules/dxp/apps/osb/osb-faro/osb-faro-contacts-demo/bnd.bnd, modules/dxp/apps/osb/osb-faro/osb-faro-contacts-demo/build.gradle, modules/dxp/apps/osb/osb-faro/osb-faro-contacts-service/bnd.bnd, modules/dxp/apps/osb/osb-faro/osb-faro-contacts-service/build.gradle, modules/dxp/apps/osb/osb-faro/osb-faro-docker/common/resources/portal-ext.properties, modules/dxp/apps/osb/osb-faro/osb-faro-docker/local/Dockerfile, modules/dxp/apps/osb/osb-faro/osb-faro-engine-client/bnd.bnd, modules/dxp/apps/osb/osb-faro/osb-faro-engine-client/build.gradle, modules/dxp/apps/osb/osb-faro/osb-faro-login-web-fragment/bnd.bnd, modules/dxp/apps/osb/osb-faro/osb-faro-mock-engine-client/bnd.bnd, modules/dxp/apps/osb/osb-faro/osb-faro-mock-engine-client/build.gradle, modules/dxp/apps/osb/osb-faro/osb-faro-mock-provisioning-client/bnd.bnd, modules/dxp/apps/osb/osb-faro/osb-faro-mock-provisioning-client/build.gradle, modules/dxp/apps/osb/osb-faro/osb-faro-provisioning-client/bnd.bnd, modules/dxp/apps/osb/osb-faro/osb-faro-provisioning-client/build.gradle, modules/dxp/apps/osb/osb-faro/osb-faro-service/bnd.bnd, modules/dxp/apps/osb/osb-faro/osb-faro-service/build.gradle, modules/dxp/apps/osb/osb-faro/osb-faro-test/bnd.bnd, modules/dxp/apps/osb/osb-faro/osb-faro-web/bnd.bnd, modules/dxp/apps/osb/osb-faro/osb-faro-web/build.gradle, modules/dxp/apps/osb/osb-faro/wedeploy/dev/Dockerfile, modules/dxp/apps/osb/osb-faro/wedeploy/prd/Dockerfile, modules/dxp/apps/osb/osb-faro/wedeploy/uat/Dockerfile
Jira ticket: https://issues.liferay.com/browse/LRAC-14791
=> LRAC-14791 | faro-v4.3.x

modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/contacts/components/ActivitiesChart.tsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/contacts/components/ActivitiesChartDeprecated.tsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/experiments/components/LineChart.tsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/individual/dashboard/components/ActiveIndividualsChart.tsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/settings/components/data-transformation-list/Row.jsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/components/download-report/utils.ts, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/components/metric-card/MetricTooltipt.tsx
- LRAC-15007 Follow up - return null to render tooltip component correctly after upgrading recharts version
- LRAC-14899 Change Analytics Cloud text color in the PDF
=> faro v4.4.x changes 3

modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/contacts/components/ActivitiesChart.tsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/contacts/components/ActivitiesChartDeprecated.tsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/individual/dashboard/components/ActiveIndividualsChart.tsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/segment/components/Growth.tsx
- LRAC-15023 Return null to render tooltip component correctly after upgrading recharts version
- LRAC-15024 Add type number on AxisX after upgrading recharts version
=> faro v4.4.x changes 4

modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/components/modals/SearchableEntitiesTableModal.tsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/util/request.js
- LRAC-15177 Remove undefined values from object before make request
- LRAC-15177 Add modal body to avoid hidden scroll
=> faro v4.4.x LRAC 15177

modules/dxp/apps/osb/osb-faro/osb-faro-engine-client/src/main/java/com/liferay/osb/faro/engine/client/model/credentials/TokenCredentials.java
Jira ticket: https://issues.liferay.com/browse/LRAC-14955
=> LRAC-14955 | faro-v4.5.x

modules/dxp/apps/osb/osb-faro/osb-faro-admin-web/bnd.bnd
Jira ticket: https://issues.liferay.com/browse/LPD-15497
=> LPD-15497 | faro-v4.6.x

modules/dxp/apps/osb/osb-faro/osb-faro-api/src/main/java/com/liferay/osb/faro/model/FaroProjectModel.java, modules/dxp/apps/osb/osb-faro/osb-faro-api/src/main/java/com/liferay/osb/faro/model/FaroProjectTable.java, modules/dxp/apps/osb/osb-faro/osb-faro-api/src/main/java/com/liferay/osb/faro/model/FaroProjectWrapper.java, modules/dxp/apps/osb/osb-faro/osb-faro-service/bnd.bnd, modules/dxp/apps/osb/osb-faro/osb-faro-service/service.xml, modules/dxp/apps/osb/osb-faro/osb-faro-service/src/main/java/com/liferay/osb/faro/internal/upgrade/registry/FaroServiceUpgradeStepRegistrator.java, modules/dxp/apps/osb/osb-faro/osb-faro-service/src/main/java/com/liferay/osb/faro/internal/upgrade/v19_0_0/UpgradeFaroProjectUpgradeProcess.java, modules/dxp/apps/osb/osb-faro/osb-faro-service/src/main/java/com/liferay/osb/faro/model/impl/FaroProjectCacheModel.java, modules/dxp/apps/osb/osb-faro/osb-faro-service/src/main/java/com/liferay/osb/faro/model/impl/FaroProjectModelImpl.java, modules/dxp/apps/osb/osb-faro/osb-faro-service/src/main/java/com/liferay/osb/faro/service/impl/FaroProjectLocalServiceImpl.java, modules/dxp/apps/osb/osb-faro/osb-faro-service/src/main/resources/META-INF/module-hbm.xml, modules/dxp/apps/osb/osb-faro/osb-faro-service/src/main/resources/META-INF/portlet-model-hints.xml, modules/dxp/apps/osb/osb-faro/osb-faro-service/src/main/resources/META-INF/sql/tables.sql
Jira ticket: https://issues.liferay.com/browse/LPD-6913
=> LPD-6913 | faro-v4.6.x

modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/main/FaroSubscriptionDisplay.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/search/FaroProjectIndexer.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/settings/components/usage-overview/PlanBreakdown.jsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/settings/components/usage-overview/PlansList.jsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/settings/pages/UsageOverview.jsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/util/__tests__/subscriptions.js
Jira ticket: https://issues.liferay.com/browse/LPD-6573
=> LPD-6573 | faro-v4.6.x

build-test-analytics-cloud.xml
https://liferay.atlassian.net/browse/LRCI-4046
=> LRCI-4046 Download the gradle wrapper if available for Analytics Cloud

modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/main/FaroSubscriptionDisplay.java
Jira ticket: https://issues.liferay.com/browse/LPD-1171
=> LPD-1171 | faro-v4.6.x

portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACIndividualsDashboard.macro, portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACUtils.macro, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/ConnectionPropertyList.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/CustomEventsSavingAnalysis.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/PageProfilePath.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/PagesList.testcase
https://liferay.atlassian.net/browse/LPD-16387
=> LPD-16387 - Backport AC Test Fix To 4.6.x

modules/apps/analytics/analytics-settings-impl/src/main/java/com/liferay/analytics/settings/internal/configuration/AnalyticsConfigurationRegistryImpl.java, modules/apps/analytics/analytics-settings-rest-api/bnd.bnd, modules/apps/analytics/analytics-settings-rest-api/src/main/java/com/liferay/analytics/settings/rest/manager/AnalyticsSettingsManager.java, modules/apps/analytics/analytics-settings-rest-api/src/main/resources/com/liferay/analytics/settings/rest/manager/packageinfo, modules/apps/analytics/analytics-settings-rest-impl/src/main/java/com/liferay/analytics/settings/rest/internal/manager/AnalyticsSettingsManagerImpl.java
Jira ticket: https://issues.liferay.com/browse/LRAC-15333
=> LRAC-15333 | faro-v4.6.x

modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/css/_utils.scss, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/components/modals/NewRequestModal.tsx
- Revert "LPD-17115 Follow up - Use Promise instead async"
- LPD-17115 Follow up - fix id
- LPD-17115 Force dropdowns appears on top of old modals
=> LPD-17115 | 4.6.x Followup

modules/apps/analytics/analytics-batch-export-import-impl/src/main/java/com/liferay/analytics/batch/exportimport/internal/dto/v1_0/converter/DXPEntityDTOConverterImpl.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/segment/segment-editor/dynamic/utils/odata.ts
Jira ticket: https://issues.liferay.com/browse/LPD-16635
=> LPD-16635 | faro-v4.6.x

modules/apps/frontend-taglib/frontend-taglib/build.gradle, modules/dxp/apps/osb/osb-faro/osb-faro-admin-web/build.gradle, modules/dxp/apps/osb/osb-faro/osb-faro-admin-web/src/main/java/com/liferay/osb/faro/admin/web/internal/model/FaroProjectAdminDisplay.java, modules/dxp/apps/osb/osb-faro/osb-faro-admin-web/src/main/java/com/liferay/osb/faro/admin/web/internal/portlet/action/InfoPanelMVCResourceCommand.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/search/FaroProjectIndexer.java
Jira ticket: https://issues.liferay.com/browse/LPD-18200
=> LPD-18200 | faro-v4.7.x

modules/dxp/apps/osb/osb-faro/osb-faro-engine-client/src/main/java/com/liferay/osb/faro/engine/client/ContactsEngineClient.java, modules/dxp/apps/osb/osb-faro/osb-faro-engine-client/src/main/java/com/liferay/osb/faro/engine/client/internal/ContactsEngineClientImpl.java, modules/dxp/apps/osb/osb-faro/osb-faro-engine-client/src/main/java/com/liferay/osb/faro/engine/client/model/Rels.java, modules/dxp/apps/osb/osb-faro/osb-faro-mock-engine-client/src/main/java/com/liferay/osb/faro/mock/engine/client/internal/BaseMockContactsEngineClientImpl.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/main/FaroSubscriptionDisplay.java
Jira ticket: https://issues.liferay.com/browse/LPD-18456
=> LPD-18456 | faro-v4.7.x

modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/constants/FaroMessageDestinationNames.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/controller/main/ProjectController.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/messaging/UpdateFaroProjectSubscriptionsMessageListener.java
Jira ticket: https://issues.liferay.com/browse/LPD-1210
=> LPD-1210 | faro-v4.7.x

portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACDefinitions.macro
https://liferay.atlassian.net/browse/LPD-18537
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2543606450&testrayRunId=2543606460)
=> Backport | AC Test Fix - LPD-18537 | master

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/IndividualsEnrichedProfiles.testcase
https://liferay.atlassian.net/browse/LPD-17406
=> Backport | AC Test Fix - LPD-17406 | master

modules/dxp/apps/osb/osb-faro/osb-faro-provisioning-client/src/main/java/com/liferay/osb/faro/provisioning/client/constants/ProductConstants.java, modules/dxp/apps/osb/osb-faro/osb-faro-service/src/main/java/com/liferay/osb/faro/service/impl/FaroUserLocalServiceImpl.java
Jira ticket: https://issues.liferay.com/browse/LPD-18468
=> LPD-18468 | faro-v4.6.x

modules/dxp/apps/osb/osb-faro/osb-faro-web/package.json, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/event-analysis/components/event-analysis-editor/event-analysis-builder/__tests__/__snapshots__/AttributeFilterSection.jsx.snap, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/event-analysis/components/event-analysis-editor/event-analysis-builder/attribute-filter-dropdown/filter/__tests__/__snapshots__/FilterOptions.jsx.snap, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/event-analysis/components/event-analysis-editor/event-analysis-builder/attribute-filter-dropdown/filter/__tests__/__snapshots__/StringFilter.jsx.snap, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/event-analysis/pages/__tests__/__snapshots__/Edit.jsx.snap, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/segment/segment-editor/dynamic/criteria-builder/__tests__/__snapshots__/CriteriaRow.jsx.snap, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/segment/segment-editor/dynamic/inputs/GeolocationInput.tsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/segment/segment-editor/dynamic/inputs/__tests__/__snapshots__/AccountInput.jsx.snap, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/segment/segment-editor/dynamic/inputs/__tests__/__snapshots__/CustomStringInput.jsx.snap, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/segment/segment-editor/dynamic/inputs/__tests__/__snapshots__/GeolocationInput.jsx.snap, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/segment/segment-editor/dynamic/inputs/__tests__/__snapshots__/SessionInput.jsx.snap, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/segment/segment-editor/dynamic/inputs/__tests__/__snapshots__/StringInput.jsx.snap, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/components/AutocompleteInput.tsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/components/form/AutocompleteInput.tsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/components/modals/__tests__/__snapshots__/NewRequestModal.jsx.snap, modules/dxp/apps/osb/osb-faro/yarn.lock
- LPD-18775 Add ClayAutocomplete
- LPD-18775 Use ClayAutocomplete on Autocomplete input fields
=> LPD-18775 | 4.7.x

modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/event-analysis/queries/EventDefinitionsQuery.ts, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/settings/definitions/events/components/CustomEventList.tsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/settings/definitions/events/components/__tests__/CustomEventList.jsx
Jira ticket: https://issues.liferay.com/browse/LPD-1172
=> LPD-1172 | faro-v4.7.x

portal-web/test/functional/com/liferay/portalweb/paths/analyticscloud/ACDataControlAndPrivacy.path
https://liferay.atlassian.net/browse/LPD-18528
=> Backport | AC Test Fix - LPD-18528 | master

portal-web/test/functional/com/liferay/portalweb/paths/analyticscloud/ACEventAnalysis.path
https://liferay.atlassian.net/browse/LPD-18535
=> Backport | AC Test Fix - LPD-18535 | master

portal-web/test/functional/com/liferay/portalweb/paths/analyticscloud/ACSegments.path
https://liferay.atlassian.net/browse/LPD-19094
=> Backport | AC Test Fix - LPD-19094 | master

portal-web/test/functional/com/liferay/portalweb/paths/analyticscloud/ACSegments.path
https://liferay.atlassian.net/browse/LPD-19172
=> Backport | AC Test Fix - LPD-19172 | master

portal-web/test/functional/com/liferay/portalweb/paths/analyticscloud/ACEventAnalysis.path
https://liferay.atlassian.net/browse/LPD-19179
=> Backport | AC Test Fix - LPD-19179 | master

modules/dxp/apps/osb/osb-faro/wedeploy/common/antivirus/LCP.json, modules/dxp/apps/osb/osb-faro/wedeploy/common/backup/LCP.json, modules/dxp/apps/osb/osb-faro/wedeploy/common/database/LCP.json, modules/dxp/apps/osb/osb-faro/wedeploy/common/search/LCP.json, modules/dxp/apps/osb/osb-faro/wedeploy/common/webserver/LCP.json
https://liferay.atlassian.net/browse/LPD-18952
=> LPD-1895 | 4.7.x

modules/dxp/apps/osb/osb-faro/osb-faro-provisioning-client/src/main/java/com/liferay/osb/faro/provisioning/client/internal/ProvisioningClientImpl.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/controller/main/ProjectController.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/test/java/com/liferay/osb/faro/web/internal/controller/main/ProjectControllerTest.java
Jira ticket: https://issues.liferay.com/browse/LPD-18711
=> LPD-18711 | faro-v4.7.x

modules/dxp/apps/osb/osb-faro/osb-faro-admin-web/src/main/java/com/liferay/osb/faro/admin/web/internal/model/FaroProjectAdminDisplay.java, modules/dxp/apps/osb/osb-faro/osb-faro-admin-web/src/main/java/com/liferay/osb/faro/admin/web/internal/portlet/action/InfoPanelMVCResourceCommand.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/jest.config.js, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/controller/main/ProjectController.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/messaging/UpdateFaroProjectSubscriptionsMessageListener.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/contacts/ProjectDisplay.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/main/FaroSubscriptionDisplay.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/search/FaroProjectIndexer.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/util/subscriptions.js, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/test/java/com/liferay/osb/faro/web/internal/controller/main/ProjectControllerTest.java
Jira ticket: https://issues.liferay.com/browse/LPD-17377
=> LPD-17377 | faro-v4.7.x

modules/dxp/apps/osb/osb-faro/osb-faro-admin-web/bnd.bnd
Jira ticket: https://issues.liferay.com/browse/LPD-0
=> LPD-0 | faro-v4.7.x

modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/main/FaroSubscriptionDisplay.java
Jira ticket: https://issues.liferay.com/browse/LPD-19350
=> LPD-19350 | faro-v4.7.x

modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/settings/components/usage-overview/SubscriptionDetails.tsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/settings/pages/__tests__/__snapshots__/UsageOverview.jsx.snap, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/util/__tests__/subscriptions.js, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/util/subscriptions.js, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/test/data.js
- LPD-19548 Include addOns on the usage limits for individuals and page views
- LPD-19548 Update unit test
=> LPD-19548 | 4.7.x

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/IdentityEvents.testcase
https://liferay.atlassian.net/browse/LPD-18856
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2546288304&testrayRunId=2546288341)
=> Backport | AC Test Fix - LPD-18856 | master

portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACEventAnalysis.macro, portal-web/test/functional/com/liferay/portalweb/paths/analyticscloud/ACEventAnalysis.path, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/CustomEventsEventAnalysis.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/CustomEventsFilterBreakdown.testcase
https://liferay.atlassian.net/browse/LPD-17403
=> Backport | AC Test Fix - LPD-17403 | master

modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/controller/main/ProjectController.java
Jira ticket: https://issues.liferay.com/browse/LPD-18894
=> LPD-18894 | faro-v4.7.x

portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACSettings.macro, portal-web/test/functional/com/liferay/portalweb/paths/analyticscloud/ACDataControlAndPrivacy.path, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/DataControlAndPrivacy.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/EmptyState.testcase
https://liferay.atlassian.net/browse/LPD-18954 (Ticket 1)
Bug: https://liferay.atlassian.net/browse/LRAC-13973
https://liferay.atlassian.net/browse/LPD-18950 (Ticket 2)
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2547704893&testrayRunId=2547705048)
=> Backport | AC Test Fix - LPD-18950 | master

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/DataControlAndPrivacy.testcase
https://liferay.atlassian.net/browse/LPD-19948
=> Backport | AC Test Fix - LPD-19948 | master

portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACInterests.macro, portal-web/test/functional/com/liferay/portalweb/paths/analyticscloud/ACSettings.path, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/UserManagement.testcase
https://liferay.atlassian.net/browse/LPD-19991
=> Backport | AC Test Fix - LPD-19991 | master

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/EditSegments.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/KnownIndividualsProfileSegments.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SegmentsCreation.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SegmentsCreationWebBehavior.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SegmentsMembership.testcase
https://liferay.atlassian.net/browse/LPD-18951 (Ticket)
Bug: https://liferay.atlassian.net/browse/LPD-1177
[Testray 1](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2546759792&testrayRunId=2546759941)
[Testray 2](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2547896922&testrayRunId=2547904988)
[Testray 3](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2548153807&testrayRunId=2548153863)
=> Backport | AC Test Fix - LPD-18951 | master

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/ABTestACSide.testcase
https://liferay.atlassian.net/browse/LPD-20033
=> Backport | AC Test Fix - LPD-20033 | master

portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACSegments.macro
https://liferay.atlassian.net/browse/LPD-20036
=> Backport | AC Test Fix - LPD-20036 | master

portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACCards.macro, portal-web/test/functional/com/liferay/portalweb/paths/analyticscloud/ACCards.path, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/IndividualsEnrichedProfiles.testcase
https://liferay.atlassian.net/browse/LPD-19949
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2548260964&testrayRunId=2548261010)
=> Backport | AC Test Fix - LPD-19949 | master

portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACCards.macro
https://liferay.atlassian.net/browse/LPD-19949
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2548260964&testrayRunId=2548261010)
=> Backport 2 | AC Test Fix - LPD-19949 | master

modules/dxp/apps/osb/osb-faro/osb-faro-provisioning-client/src/main/java/com/liferay/osb/faro/provisioning/client/internal/ProvisioningClientImpl.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/main/FaroSubscriptionDisplay.java
Jira ticket: https://issues.liferay.com/browse/LPD-20144
=> LPD-20144 | faro-v4.7.x

build-test-analytics-cloud.xml, test.properties
https://liferay.atlassian.net/browse/LRCI-4015
=> LRCI-4077 Add ability to save jstacks for AC to be stored in Testray

modules/dxp/apps/osb/osb-faro/wedeploy/common/search/LCP.json
Jira ticket: https://issues.liferay.com/browse/LPD-5067
=> LPD-5067 | faro-v4.7.x

modules/dxp/apps/osb/osb-faro/osb-faro-service/src/main/java/com/liferay/osb/faro/service/persistence/impl/FaroChannelFinderImpl.java
- LPD-1207 rewrites search using the "AND" operator
- LPD-1207 SF
=> Search propety list backport 4.7.x

build-test-analytics-cloud.xml
=> LRCI-4077 Add retry logic for downloading dist files for AC | faro-v4.7.x

modules/dxp/apps/osb/osb-faro/osb-faro-service/src/main/java/com/liferay/osb/faro/service/impl/FaroProjectLocalServiceImpl.java
Jira ticket: https://issues.liferay.com/browse/LPD-20478
=> LPD-20478 | faro-v4.7.x

portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACSettings.macro, portal-web/test/functional/com/liferay/portalweb/paths/analyticscloud/ACUsage.path, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/Usage.testcase
https://liferay.atlassian.net/browse/LPD-20374
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2551843761&testrayRunId=2551846305)
=> Backport | AC Test Fix - LPD-20374 | master

portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACNavigation.macro
https://liferay.atlassian.net/browse/LPD-20606
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2551849112&testrayRunId=2551850374)
=> Backport | AC Test Fix - LPD-20606 | master

build-test-analytics-cloud.xml, test.properties
=> LRCI-4077 Backport AC Fixes to Release & Legacy branches | faro-v4.7.x

portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACTests.macro, portal-web/test/functional/com/liferay/portalweb/paths/analyticscloud/ACTests.path, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/ABTestACSide.testcase
https://liferay.atlassian.net/browse/LPD-20607
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2551941759&testrayRunId=2551941819)
=> Backport | AC Test Fix - LPD-20607 | master

modules/dxp/apps/osb/osb-faro/osb-faro-engine-client/src/main/java/com/liferay/osb/faro/engine/client/ContactsEngineClient.java, modules/dxp/apps/osb/osb-faro/osb-faro-engine-client/src/main/java/com/liferay/osb/faro/engine/client/internal/ContactsEngineClientImpl.java, modules/dxp/apps/osb/osb-faro/osb-faro-engine-client/src/main/java/com/liferay/osb/faro/engine/client/model/Rels.java, modules/dxp/apps/osb/osb-faro/osb-faro-mock-engine-client/src/main/java/com/liferay/osb/faro/mock/engine/client/internal/BaseMockContactsEngineClientImpl.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/main/FaroSubscriptionDisplay.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/settings/components/usage-overview/KnownIndividualsSession.tsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/util/subscriptions.js, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/resources/META-INF/resources/init.jsp, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/resources/META-INF/resources/view.jsp
Jira ticket: https://issues.liferay.com/browse/LPD-20251
=> LPD-20251 | faro-v4.7.x

portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACUtils.macro, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/CustomEventsBlockEvents.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/CustomEventsSavingAnalysis.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/EmailReport.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/InviteUsers.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/Properties.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SitesPropertyAnalyticsFilter.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/UserManagement.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/UserManagementDelete.testcase
https://liferay.atlassian.net/browse/LPD-19934
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2552406430&testrayRunId=2552406467)
=> Backport | AC Test Fix - LPD-19934 | master

portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACEventAnalysis.macro
https://liferay.atlassian.net/browse/LPD-20624
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2552614738&testrayRunId=2552614805)
=> Backport | AC Test Fix - LPD-20624 | master

portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACDXPSettings.macro, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SyncAttributes.testcase
https://liferay.atlassian.net/browse/LPD-20620
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2552788134&testrayRunId=2552788155)
=> Backport | AC Test Fix - LPD-20620 | master

portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACAssets.macro, portal-web/test/functional/com/liferay/portalweb/paths/analyticscloud/ACAssets.path, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/AssetsWebContent.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/CustomEventsEventAnalysis.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/CustomEventsFilterBreakdown.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/IdentityEvents.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/PagesList.testcase
https://liferay.atlassian.net/browse/LPD-20627
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2553238897&testrayRunId=2553239567)
=> Backport | AC Test Fix - LPD-20627 | master

portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACSegments.macro, portal-web/test/functional/com/liferay/portalweb/paths/analyticscloud/ACSegments.path, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/ActiveIndividuals.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/AssetsBlogs.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/AssetsForms.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/AssetsWebContent.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/DataReportAPI.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/DeleteSegments.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/EditSegments.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/IdentityEvents.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/KnownIndividualsProfileSegments.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/KnownIndividualsSearch.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/PageProfilePath.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/PagesList.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SegmentsCreation.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SegmentsCreationIndividualAttributes.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SegmentsDistribution.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SegmentsOverviewAttributeBreakdown.testcase
https://liferay.atlassian.net/browse/LPD-20629
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2553202217&testrayRunId=2553202286)
[`faro-v4.7.x` branch was missing these commits that were already in the `master` branch](https://github.com/liferay/liferay-portal/commits/master/portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SegmentsOverviewAttributeBreakdown.testcase):
- https://github.com/liferay/liferay-portal/commit/7281873212847622d15a5a421c0bbfd54b13a7e0
- https://github.com/liferay/liferay-portal/commit/9fcdce2c9aacca3d3a8ac6e2ebaf4c1bcd6ed1b5
=> Backport | AC Test Fix - LPD-20629 | master

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/DataReportAPI.testcase
https://liferay.atlassian.net/browse/LPD-21024
=> Backport | AC Test Fix - LPD-21024 | master

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/DefinitionsSearch.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SearchAPI.testcase
https://liferay.atlassian.net/browse/LPD-20630
=> Backport | AC Test Fix - LPD-20630 | master

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/AssetsBlogs.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/EditSegments.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/KnownIndividualsProfileSegments.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/KnownIndividualsSearch.testcase
https://liferay.atlassian.net/browse/LPD-20629
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2553202217&testrayRunId=2553202286)
=> Backport 2 | AC Test Fix - LPD-20629 | master

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/AssetsCustomAsset.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/PageProfilePath.testcase
https://liferay.atlassian.net/browse/LPD-20627
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2553238897&testrayRunId=2553239567)
=> Backport 2 | AC Test Fix - LPD-20627 | master

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SearchAPI.testcase
https://liferay.atlassian.net/browse/LPD-20630
=> Backport 2 | AC Test Fix - LPD-20630 | master

portal-web/test/functional/com/liferay/portalweb/tests/enduser/abtest/ABTesting.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentdashboard/ContentDashboardWithAC.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentperformance/ContentPerformance.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentperformance/ContentPerformanceWithoutAC.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/contentperformance/ContentPerformanceWithoutButtonCD.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/segmentation/ACSegmentsInDXP.testcase
=> LRCI-4077 Remove property from poshi tests

portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACDefinitions.macro, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/DefinitionsSearch.testcase
https://liferay.atlassian.net/browse/LPD-20623
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2553788252&testrayRunId=2553797697)
=> Backport | AC Test Fix - LPD-20623 | master

portal-web/test/functional/com/liferay/portalweb/functions/AssertTextNotEquals.function
=> LRCI-4077 Add missing function

portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACEventAnalysis.macro, portal-web/test/functional/com/liferay/portalweb/paths/analyticscloud/ACEventAnalysis.path, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/CustomEventsEventAnalysis.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/CustomEventsFilterBreakdown.testcase
https://liferay.atlassian.net/browse/LPD-19935
[Testray 1](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2553786581)
[Testray 2](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2554519647)
=> Backport | AC Test Fix - LPD-19935 | master

build-test-analytics-cloud.xml, test.properties
https://liferay.atlassian.net/browse/LRCI-4076
=> LRCI-4076 Remove retry counter for dumping the log file

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/AssetsCustomAsset.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/CustomEventsEventAnalysis.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/DataReportAPI.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/IndividualsDashboard.testcase
https://liferay.atlassian.net/browse/LPD-20627
=> Backport 3 | AC Test Fix - LPD-20627 | master

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/ABTestACSide.testcase
https://liferay.atlassian.net/browse/LPD-21016
=> Backport | AC Test Fix - LPD-21016 | master

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/CustomEventsBlockedEventsList.testcase
https://liferay.atlassian.net/browse/LPD-19947
=> Backport | AC Test Fix - LPD-19947 | master

modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/individual/dashboard/pages/__tests__/__snapshots__/InterestDetails.jsx.snap, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/components/__tests__/__snapshots__/InterestDetails.jsx.snap, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/util/table-columns.tsx
- LPD-20256 Remove encodeURIComponent from touchpoint and title
- LPD-20256 Use decodeURIComponent into renderSecondaryInfo
- LPD-20256 Update snapshots
=> LPD-20256 | 4.8.x

portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACAssets.macro, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/AssetsBlogs.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/CustomEventsSavingAnalysis.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/IdentityEvents.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/IndividualsEnrichedProfiles.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SyncContactsAndAccounts.testcase
https://liferay.atlassian.net/browse/LPD-21869
=> Backport | AC Test Fix - LPD-21869 | master

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/KnownIndividualsProfileDetails.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/PageProfilePath.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SegmentsCreationIndividualAttributes.testcase
https://liferay.atlassian.net/browse/LPD-21869
=> Backport | AC Test Fix 2 - LPD-21869 | master

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SyncSitesAndChannels.testcase
https://liferay.atlassian.net/browse/LPD-22027
=> Backport | AC Test Fix - LPD-22027 | master

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SearchAPI.testcase
https://liferay.atlassian.net/browse/LPD-20630
=> Backport | AC Test Fix 2 - LPD-20630 | master

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/EditSegments.testcase
https://liferay.atlassian.net/browse/LPD-21561
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2558294597&testrayRunId=2558297394)
=> Backport | AC Test Fix - LPD-21561 | master

portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACAssets.macro, portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACCards.macro, portal-web/test/functional/com/liferay/portalweb/paths/analyticscloud/ACAssets.path, portal-web/test/functional/com/liferay/portalweb/paths/analyticscloud/ACCards.path, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/AssetsWebContent.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/CustomEventsUnblockEvents.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/DataReportAPI.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/IdentityEvents.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/IndividualsDashboard.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/PageProfileVisitorBehavior.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SegmentsMembership.testcase
https://liferay.atlassian.net/browse/LPD-20627
=> Backport | AC Test Fix 4 - LPD-20627 | master

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SearchAPI.testcase
https://liferay.atlassian.net/browse/LPD-20630
=> Backport | AC Test Fix 3 - LPD-20630 | master

modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/apollo/client.js, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/hooks/useCurrentUser.ts
- LPD-22265 Fix useCurrentUser to use friendly workspace url
- LPD-22265 Enable apollo devtools in the FARO dev mode
=> LPD-22265 | 4.8.x

portal-web/test/functional/com/liferay/portalweb/macros/ABTest.macro, portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACSettings.macro, portal-web/test/functional/com/liferay/portalweb/paths/portlet/abtest/ABTest.path, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/ABTestACSide.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/ABTestDXPSide.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/CustomEventsAttributeSettings.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/CustomEventsGlobalAttributes.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/CustomEventsSavingAnalysis.testcase
https://liferay.atlassian.net/browse/LCD-36947
=> Backport | AC Test Fix - LCD-36947 | master

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/CustomEventsEventAnalysis.testcase
https://liferay.atlassian.net/browse/LCD-36952
=> Backport | AC Test Fix - LCD-36952 | master

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/DefinitionsSearch.testcase
https://liferay.atlassian.net/browse/LCD-36971
=> Backport | AC Test Fix - LCD-36971 | master

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/CustomEventsSavingAnalysis.testcase
https://liferay.atlassian.net/browse/LCD-36973
=> Backport | AC Test Fix - LCD-36973 | master

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SitesPropertyAnalyticsFilter.testcase
https://liferay.atlassian.net/browse/LCD-36974
=> Backport | AC Test Fix - LCD-36974 | master

portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACUtils.macro, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SegmentsCreationWebBehavior.testcase
https://liferay.atlassian.net/browse/LCD-36980
=> Backport | AC Test Fix - LCD-36980 | master

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SyncSitesAndChannels.testcase
https://liferay.atlassian.net/browse/LPD-20620
=> Backport | AC Test Fix 2 - LPD-20620 | master

portal-web/test/functional/com/liferay/portalweb/macros/ABTest.macro
https://liferay.atlassian.net/browse/LCD-36981
=> Backport | AC Test Fix - LCD-36981 | master

modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/hooks/useCurrentUser.ts, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/util/__tests__/__snapshots__/subscriptions.js.snap
- LPD-20960 Update snapshot
- LPD-20960 Returns a new user when current user request error
=> LPD-20960 | 4.8.x

portal-web/test/functional/com/liferay/portalweb/paths/portlet/abtest/ABTest.path
https://liferay.atlassian.net/browse/LCD-36981
=> Backport | AC Test Fix 2 - LCD-36981 | master

modules/dxp/apps/osb/osb-faro/osb-faro-admin-web/build.gradle, modules/dxp/apps/osb/osb-faro/osb-faro-api/build.gradle, modules/dxp/apps/osb/osb-faro/osb-faro-contacts-api/build.gradle, modules/dxp/apps/osb/osb-faro/osb-faro-contacts-demo/build.gradle, modules/dxp/apps/osb/osb-faro/osb-faro-contacts-service/build.gradle, modules/dxp/apps/osb/osb-faro/osb-faro-docker/local/Dockerfile, modules/dxp/apps/osb/osb-faro/osb-faro-engine-client/build.gradle, modules/dxp/apps/osb/osb-faro/osb-faro-mock-engine-client/build.gradle, modules/dxp/apps/osb/osb-faro/osb-faro-mock-provisioning-client/build.gradle, modules/dxp/apps/osb/osb-faro/osb-faro-provisioning-client/build.gradle, modules/dxp/apps/osb/osb-faro/osb-faro-service/build.gradle, modules/dxp/apps/osb/osb-faro/osb-faro-web/build.gradle, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/activator/OAuth2AuthorizationExpandoPortalInstanceLifecycleListener.java
https://liferay.atlassian.net/browse/LPD-22669
=> LPD-22669 | faro-v4.7.x

modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/sites/touchpoints/components/sankey/EmptySankey.tsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/sites/touchpoints/components/sankey/Node.tsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/sites/touchpoints/components/sankey/PagePathCard.tsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/sites/touchpoints/components/sankey/Sankey.tsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/sites/touchpoints/components/sankey/__tests__/PagePathCard.tsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/test/graphql-data.js
- LPD-16566 Get rangeSelectors from dropdown range key instead of URL
- LPD-16566 Add new unit tests
=> LPD-16566 | 4.8.x

ci.properties
https://liferay.atlassian.net/browse/LRCI-4163
=> LRCI-4163 Add AC suites to the list of available test suites

portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACSegments.macro, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SegmentsOverviewAttributeBreakdown.testcase
https://liferay.atlassian.net/browse/LCD-37480
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2563988368&testrayRunId=2563988591)
=> Backport | AC Test Fix - LCD-37480 | master

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/IndividualsDashboard.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SegmentsCreation.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SegmentsCreationWebBehavior.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SegmentsDistribution.testcase
https://liferay.atlassian.net/browse/LCD-37479
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2564321022&testrayRunId=2564321089)
=> Backport | AC Test Fix - LCD-37479 | master

modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/util/__tests__/util.js, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/util/mappers.js, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/util/table-columns.tsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/util/util.ts, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/sites/touchpoints/components/sankey/Node.tsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/sites/touchpoints/components/sankey/PagePathCard.tsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/sites/touchpoints/hocs/mappers/touchpoint-assets-list-query.js
- LPD-24247 Create getSafeTouchpoint util and use it
- LPD-24247 Fix encodes / decodes
- LPD-24247 Create getSafeTouchpoint unit test
=> LPD-24247 | 4.8.x

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/DataReportAPI.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SyncContactsAndAccounts.testcase
https://liferay.atlassian.net/browse/LCD-37479
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2564534424&testrayRunId=2564534637)
=> Backport | AC Test Fix 2 - LCD-37479 | master

modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/util/__tests__/util.js, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/util/util.ts
- LPD-24247 Fix getSafeTouchpoint to http://liferay.com do not returns with / at the end of URL
- LPD-24247 Add more unit tests to coverage other cases
=> LPD-24247 | 4.8.x Follow Up

portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACNavigation.macro, portal-web/test/functional/com/liferay/portalweb/paths/analyticscloud/ACNavigation.path, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/PageProfilePath.testcase
https://liferay.atlassian.net/browse/LCD-37616
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2565197959&testrayRunId=2565199409)
=> Backport | AC Test Fix - LCD-37616 | master

portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACSegments.macro, portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACUtils.macro, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SegmentsCreationWebBehavior.testcase
https://liferay.atlassian.net/browse/LCD-37743
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2566642654&testrayRunId=2566642665)
=> Backport | AC Test Fix - LCD-37743 | master

portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACPagePath.macro, portal-web/test/functional/com/liferay/portalweb/paths/analyticscloud/ACPagePath.path, portal-web/test/functional/com/liferay/portalweb/paths/analyticscloud/ACSites.path, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/PageProfilePath.testcase
https://liferay.atlassian.net/browse/LCD-37703
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2566648481&testrayRunId=2566648498)
=> Backport | AC Test Fix - LCD-37703 | master

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SegmentsCompositionOverview.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SegmentsCreation.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SegmentsCreationWebBehavior.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SegmentsDistribution.testcase
https://liferay.atlassian.net/browse/LCD-37706
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2566715382&testrayRunId=2566715422)
=> Backport | AC Test Fix - LCD-37706 | master

portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACSegments.macro
https://liferay.atlassian.net/browse/LCD-37480
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2566847031&testrayRunId=2566847079)
=> Backport | AC Test Fix 2 - LCD-37480 | master

portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACUtils.macro, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SegmentsCompositionOverview.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SegmentsCreationWebBehavior.testcase
https://liferay.atlassian.net/browse/LCD-37792
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2567276962&testrayRunId=2567276966)
=> Backport | AC Test Fix - LCD-37792 | master

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/PagesList.testcase
https://liferay.atlassian.net/browse/LCD-37793
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2567276962&testrayRunId=2567276966)
=> Backport | AC Test Fix - LCD-37793 | master

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/PageProfilePath.testcase
https://liferay.atlassian.net/browse/LCD-37814
=> Backport | AC Test Fix - LCD-37814 | master

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SyncContactsAndAccounts.testcase
https://liferay.atlassian.net/browse/LCD-37794
=> Backport | AC Test Fix - LCD-37794 | master

portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACApi.macro
https://liferay.atlassian.net/browse/LCD-37900
=> AC Test Fix - LCD-37900 | master

portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACSegments.macro
https://liferay.atlassian.net/browse/LCD-37899
=> Backport | AC Test Fix - LCD-37899 | master

portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACUtils.macro
https://liferay.atlassian.net/browse/LCD-37907
=> Backport | AC Test Fix - LCD-37907

modules/dxp/apps/osb/osb-faro/osb-faro-engine-client/src/main/java/com/liferay/osb/faro/engine/client/model/Individual.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/contacts/IndividualDisplay.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/main/FaroSubscriptionDisplay.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/individual/profile/components/DetailsCard.jsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/individual/profile/components/__tests__/__snapshots__/DetailsCard.jsx.snap, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/util/records/Individual.ts, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/test/data.js
https://liferay.atlassian.net/browse/LPD-24609
https://liferay.atlassian.net/browse/LPD-25384
=> LPD-24609/LPD-25384 | 4.7.x

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/DataControlAndPrivacy.testcase
https://liferay.atlassian.net/browse/LCD-38030
=> Backport | AC Test Fix - LCD-38030 | master

portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACAssets.macro, portal-web/test/functional/com/liferay/portalweb/paths/analyticscloud/ACAssets.path, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/AssetsBlogs.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/AssetsDocumentsAndMedia.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/AssetsForms.testcase, portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/AssetsWebContent.testcase
https://liferay.atlassian.net/browse/LCD-38136
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2571090692&testrayRunId=2571090747)
=> Backport | AC Test Fix - LCD-38136 | master

build-test-analytics-cloud.xml
**Ticket:**
- https://liferay.atlassian.net/browse/LCD-38177
**Testray Execution:**
- [Acceptance](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2570136587&testrayRunId=2570136638)
- [AC Test Suite](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2570791054&testrayRunId=2570791124)
**Performance:**
- [Before the changes](https://testray.liferay.com/reports/production/logs/2024-05/test-1-28/test-portal-acceptance-pullrequest(master)/9431/jenkins-report.html.gz?authuser=0)
- [After the changes](https://testray.liferay.com/reports/production/logs/2024-05/test-1-27/test-portal-acceptance-pullrequest(master)/11929/jenkins-report.html.gz?authuser=0)
=> Backport | AC Test Improvement - LCD-38178 | master

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SegmentsCreation.testcase
https://liferay.atlassian.net/browse/LCD-38206
=> Backport | AC Test Fix - LCD-38206 | master

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/CustomEventsIndividuals.testcase
https://liferay.atlassian.net/browse/LCD-38205
=> Backport | AC Test Fix - LCD-38205 | master

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/PageProfilePath.testcase
https://liferay.atlassian.net/browse/LCD-38223
=> Backport | AC Test Fix - LCD-38223 | master

modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/segment/components/criteria-card/display-components/ReferencedEntityDisplay.tsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/segment/segment-editor/dynamic/inputs/BehaviorInput.tsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/segment/segment-editor/dynamic/utils/__tests__/utils.js, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/segment/segment-editor/dynamic/utils/utils.ts
Jira ticket: https://liferay.atlassian.net/browse/LPD-26796
=> LPD-26796 | faro-v4.7.x

modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/segment/components/criteria-card/display-components/ReferencedEntityDisplay.tsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/segment/segment-editor/dynamic/inputs/BehaviorInput.tsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/segment/segment-editor/dynamic/utils/__tests__/utils.js, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/segment/segment-editor/dynamic/utils/utils.ts
Jira ticket: https://liferay.atlassian.net/browse/LPD-26796
=> LPD-26796 | faro-v4.8.x

portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SyncContactsAndAccounts.testcase
https://liferay.atlassian.net/browse/LCD-38379
=> Backport | AC Test Fix - LCD-38379 | master

modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/segment/components/criteria-card/CriteriaView.tsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/segment/components/criteria-card/__tests__/CriteriaView.jsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/segment/components/criteria-card/__tests__/__snapshots__/CriteriaView.jsx.snap, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/segment/components/criteria-card/index.tsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/segment/segment-editor/dynamic/utils/__tests__/odata.js
- LPD-24099 Format criteria to include double quotes on Criteria View Card
- LPD-24099 Create unit tests
=> LPD-24099 | 4.8.x

test.properties
https://liferay.atlassian.net/browse/LCD-38414
=> Backport | AC Test Fix - LCD-38414 | master

modules/test/playwright/tests/analytics-web/supportLiferayCookieManager.spec.ts
https://liferay.atlassian.net/browse/LCD-38452
=> Backport | AC Test Fix - LCD-38452 | master

modules/dxp/apps/osb/osb-faro/osb-faro-docker/cloud/Dockerfile, modules/dxp/apps/osb/osb-faro/osb-faro-docker/local/Dockerfile
https://liferay.atlassian.net/browse/LPD-31392
=> LPD-31392 Update base DXP image to U124 | 4.8.x

modules/dxp/apps/osb/osb-faro/osb-faro-docker/cloud/Dockerfile, modules/dxp/apps/osb/osb-faro/osb-faro-docker/local/Dockerfile
https://liferay.atlassian.net/browse/LPD-31392
=> LPD-31392 Update base image from U122 to U124 | 4.9.x

build.xml
https://liferay.atlassian.net/browse/LPD-2443
=> LPD-2443 Backport | 4.9.x

modules/dxp/apps/osb/osb-faro/osb-faro-engine-client/src/main/java/com/liferay/osb/faro/engine/client/ContactsEngineClient.java, modules/dxp/apps/osb/osb-faro/osb-faro-engine-client/src/main/java/com/liferay/osb/faro/engine/client/internal/ContactsEngineClientImpl.java, modules/dxp/apps/osb/osb-faro/osb-faro-engine-client/src/main/java/com/liferay/osb/faro/engine/client/model/Rels.java, modules/dxp/apps/osb/osb-faro/osb-faro-mock-engine-client/src/main/java/com/liferay/osb/faro/mock/engine/client/internal/MockContactsEngineClientImpl.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/controller/main/ProjectController.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/messaging/UpdateFaroProjectSubscriptionsMessageListener.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/contacts/ProjectUsageDisplay.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/main/FaroSubscriptionDisplay.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/test/java/com/liferay/osb/faro/web/internal/model/display/main/FaroSubscriptionDisplayTest.java
Jira ticket: https://liferay.atlassian.net/browse/LPD-31472-4.9.x
Asah changes: https://github.com/liferay/com-liferay-osb-asah-private/pull/5908
=> LPD-31472-4.9.x | faro-v4.9.x

modules/dxp/apps/osb/osb-faro/osb-faro-docker/cloud/Dockerfile, modules/dxp/apps/osb/osb-faro/osb-faro-docker/local/Dockerfile
https://liferay.atlassian.net/browse/LPD-31392
Reverting and cherry picking change to 4.9.x. See https://github.com/liferay-ac/liferay-portal/pull/1709
=> LPD-31392 Revert base image update | 4.8.x

build.xml, modules/dxp/apps/osb/osb-faro/osb-faro-engine-client/src/main/java/com/liferay/osb/faro/engine/client/model/Individual.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/contacts/IndividualDisplay.java
https://liferay.atlassian.net/browse/LPD-34185
=> LPD-34185 Allow individual activities count to be nullable | 4.8.x

modules/dxp/apps/osb/osb-faro/osb-faro-engine-client/src/main/java/com/liferay/osb/faro/engine/client/model/Individual.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/contacts/IndividualDisplay.java
https://liferay.atlassian.net/browse/LPD-34185
=> LPD-34185 Allow individual activities count to be nullable | 4.9.x

modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/main/FaroSubscriptionDisplay.java
Jira ticket: https://liferay.atlassian.net/browse/LPD-31878
=> LPD-31878 | faro-v4.9.x

modules/dxp/apps/osb/osb-faro/Jenkinsfile
https://liferay.atlassian.net/browse/LPD-33929
=> LPD-33929 Fix Faro build backport | 4.8.x

modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/messaging/UpdateFaroProjectSubscriptionsMessageListener.java
Jira ticket: https://liferay.atlassian.net/browse/LPD-31877
=> LPD-31877 | faro-v4.9.x

modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/contacts/ProjectUsageDisplay.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/test/java/com/liferay/osb/faro/web/internal/model/display/main/FaroUsageDisplayTest.java
Jira ticket: https://liferay.atlassian.net/browse/LPD-36366
=> LPD-36366 | faro-v4.9.x

modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/controller/main/ProjectController.java
Jira ticket: https://liferay.atlassian.net/browse/LPD-36992
=> LPD-36992 | faro-v4.9.x

modules/dxp/apps/osb/osb-faro/osb-faro-docker/cloud/Dockerfile, modules/dxp/apps/osb/osb-faro/osb-faro-docker/local/Dockerfile
https://liferay.atlassian.net/browse/LPD-40228
=> LPD-40228 Update base image to U128 | 4.10.x

modules/dxp/apps/osb/osb-faro/osb-faro-admin-web/src/main/java/com/liferay/osb/faro/admin/web/internal/display/context/FaroAdminDisplayContext.java
Jira ticket: https://liferay.atlassian.net/browse/LPD-40334
=> LPD-40334 | faro-v4.10.x

modules/dxp/apps/osb/osb-faro/wedeploy/common/backup/LCP.json, modules/dxp/apps/osb/osb-faro/wedeploy/common/database/LCP.json, modules/dxp/apps/osb/osb-faro/wedeploy/common/search/LCP.json, modules/dxp/apps/osb/osb-faro/wedeploy/common/webserver/LCP.json
https://liferay.atlassian.net/browse/LPD-34966
=> LPD-34966 Update service versions | 4.9.x

modules/dxp/apps/osb/osb-faro/osb-faro-engine-client/src/main/java/com/liferay/osb/faro/engine/client/ContactsEngineClient.java, modules/dxp/apps/osb/osb-faro/osb-faro-engine-client/src/main/java/com/liferay/osb/faro/engine/client/internal/ContactsEngineClientImpl.java, modules/dxp/apps/osb/osb-faro/osb-faro-mock-engine-client/src/main/java/com/liferay/osb/faro/mock/engine/client/internal/BaseMockContactsEngineClientImpl.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/controller/contacts/InterestController.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/segment/segment-editor/dynamic/hoc/WithPropertyGroups.tsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/api/interests.js, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/components/modals/NewRequestModal.tsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/components/modals/__tests__/NewRequestModal.jsx
Jira ticket: https://liferay.atlassian.net/browse/backport
=> backport | faro-v4.10.x

modules/dxp/apps/osb/osb-faro/osb-faro-service/src/main/java/com/liferay/osb/faro/service/impl/FaroChannelLocalServiceImpl.java, modules/dxp/apps/osb/osb-faro/osb-faro-service/src/main/java/com/liferay/osb/faro/service/impl/FaroProjectLocalServiceImpl.java, modules/dxp/apps/osb/osb-faro/osb-faro-service/src/main/java/com/liferay/osb/faro/service/impl/FaroUserLocalServiceImpl.java, modules/dxp/apps/osb/osb-faro/osb-faro-service/src/main/resources/com/liferay/osb/faro/dependencies/created-workspace.html, modules/dxp/apps/osb/osb-faro/osb-faro-service/src/main/resources/com/liferay/osb/faro/dependencies/data-control-task-complete.html, modules/dxp/apps/osb/osb-faro/osb-faro-service/src/main/resources/com/liferay/osb/faro/dependencies/email-daily-report.html, modules/dxp/apps/osb/osb-faro/osb-faro-service/src/main/resources/com/liferay/osb/faro/dependencies/email-monthly-report.html, modules/dxp/apps/osb/osb-faro/osb-faro-service/src/main/resources/com/liferay/osb/faro/dependencies/email-weekly-report.html, modules/dxp/apps/osb/osb-faro/osb-faro-service/src/main/resources/com/liferay/osb/faro/dependencies/invite-existing-user.html, modules/dxp/apps/osb/osb-faro/osb-faro-service/src/main/resources/com/liferay/osb/faro/dependencies/invite-new-user.html, modules/dxp/apps/osb/osb-faro/osb-faro-service/src/main/resources/com/liferay/osb/faro/dependencies/join-request.html, modules/dxp/apps/osb/osb-faro/osb-faro-service/src/main/resources/com/liferay/osb/faro/dependencies/property-invite.html, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/templates/email/partials/onboarding/go-to-analytics-cloud-button.mjml
Jira ticket: https://liferay.atlassian.net/browse/LPD-43106
=> LPD-43106 | faro-v4.11.x

modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/controller/main/ProjectController.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/messaging/UpdateFaroProjectSubscriptionsMessageListener.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/main/FaroSubscriptionDisplay.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/test/java/com/liferay/osb/faro/web/internal/model/display/main/FaroSubscriptionDisplayTest.java
Jira ticket: https://liferay.atlassian.net/browse/LPD-46555
=> LPD-46555 | faro-v4.11.x

modules/dxp/apps/osb/osb-faro/osb-faro-docker/cloud/resources/rewrite.config, modules/dxp/apps/osb/osb-faro/osb-faro-docker/local/common/resources/rewrite.config
Jira ticket: https://liferay.atlassian.net/browse/LPD-43044
=> LPD-43044 | faro-v4.11.x

build-test-analytics-cloud.xml, modules/test/playwright/env/common.sh, modules/test/playwright/fixtures/loginAnalyticsCloudTest.ts, modules/test/playwright/tests/osb-faro-web/faro.config.ts, test.properties
More details: [LPD-44377](https://liferay.atlassian.net/browse/LPD-44377)
=> LPD-47809 | Point AC Release Tests to analytics-stg.liferay.com

modules/dxp/apps/osb/osb-faro/Jenkinsfile
https://liferay.atlassian.net/browse/LPD-51269
=> LPD-51269 Update Faro pipeline to use environment variable | 4.11.x

modules/dxp/apps/osb/osb-faro/Jenkinsfile
https://liferay.atlassian.net/browse/LPD-51269
=> LPD-51269 Update Faro pipeline to use JDK8 environment variable | 4.11.x

modules/dxp/apps/osb/osb-faro/osb-faro-docker/cloud/Dockerfile, modules/dxp/apps/osb/osb-faro/osb-faro-docker/local/Dockerfile
https://liferay.atlassian.net/browse/LPD-51643
=> LPD-51643 Update DXP base image for Faro | 4.12.0

modules/dxp/apps/osb/osb-faro/osb-faro-docker/cloud/Dockerfile, modules/dxp/apps/osb/osb-faro/osb-faro-docker/local/Dockerfile
Jira ticket: https://liferay.atlassian.net/browse/LPD-51643
=> LPD-51643 | faro-v4.12.x

modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/controller/api/GraphQLController.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/controller/api/ReportController.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/controller/api/ReportControllerResponseFactory.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/asah/FaroChannelDisplay.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/contacts/ActivityGroupDisplay.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/contacts/IndividualDisplay.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/contacts/IndividualSegmentDisplay.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/contacts/IndividualSegmentMembershipChangeDisplay.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/contacts/card/template/ActivityHistoryContactsCardTemplateDisplay.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/contacts/card/template/ClosedWonContactsCardTemplateDisplay.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/contacts/card/template/ContactsCardTemplateDisplay.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/contacts/card/template/ConversionHealthContactsCardTemplateDisplay.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/contacts/card/template/InterestContactsCardTemplateDisplay.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/contacts/card/template/LifetimeValueContactsCardTemplateDisplay.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/contacts/card/template/ProfileContactsCardTemplateDisplay.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/contacts/card/template/RecentActivitiesContactsCardTemplateDisplay.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/contacts/card/template/SegmentDistributionContactsCardTemplateDisplay.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/contacts/card/template/SegmentMembershipContactsCardTemplateDisplay.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/contacts/card/template/SimilarContactsCardTemplateDisplay.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/contacts/card/template/TouchpointAttributionContactsCardTemplateDisplay.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/servlet/GraphQLAsahServlet.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/util/MapUtil.java
- **LPD-51874 Copy MapUtil from https://github.com/liferay/liferay-portal/blob/7.4.3.128-ga128/portal-kernel/src/com/liferay/portal/kernel/util/MapUtil.java**
- **LPD-51874 Update references**
=> LPD-51874 | 4.12.x

modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/settings/data-privacy/hocs/RequestList.tsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/settings/data-privacy/hocs/__tests__/RequestList.jsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/settings/data-privacy/hocs/__tests__/__snapshots__/RequestList.jsx.snap, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/settings/data-privacy/queries/RequestListQuery.js
Jira ticket: https://liferay.atlassian.net/browse/
=>  | faro-v4.12.x

modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/controller/main/ProjectController.java
Jira ticket: https://liferay.atlassian.net/browse/LPD-53214
=> LPD-53214 | faro-v4.11.x

modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/queries/UserSessionQuery.ts, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/util/__tests__/__snapshots__/activities.jsx.snap, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/util/__tests__/activities.jsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/util/activities.tsx, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/test/data.js, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/test/graphql-data.js
Jira ticket: https://liferay.atlassian.net/browse/LPD-54433
=>  LPD-54433| faro-v4.12.x

modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/model/display/main/FaroSubscriptionDisplay.java
Jira ticket: https://liferay.atlassian.net/browse/LPD-57479
=> LPD-57479 | faro-v4.13.x

modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/controller/main/ProjectController.java
Jira ticket: https://liferay.atlassian.net/browse/LPD-62428
=> LPD-62428 | faro-v4.13.x

modules/dxp/apps/osb/osb-faro/wedeploy/common/search/LCP.json
Jira ticket: https://liferay.atlassian.net/browse/LPD-64197
=> LPD-64197 | faro-v4.14.x

modules/dxp/apps/osb/osb-faro/osb-faro-api/src/main/java/com/liferay/osb/faro/model/FaroProject.java, modules/dxp/apps/osb/osb-faro/osb-faro-api/src/main/java/com/liferay/osb/faro/model/FaroProjectWrapper.java, modules/dxp/apps/osb/osb-faro/osb-faro-engine-client/src/main/java/com/liferay/osb/faro/engine/client/BaseEngineClient.java, modules/dxp/apps/osb/osb-faro/osb-faro-engine-client/src/main/java/com/liferay/osb/faro/engine/client/ContactsEngineClient.java, modules/dxp/apps/osb/osb-faro/osb-faro-engine-client/src/main/java/com/liferay/osb/faro/engine/client/internal/ContactsEngineClientImpl.java, modules/dxp/apps/osb/osb-faro/osb-faro-engine-client/src/main/java/com/liferay/osb/faro/engine/client/model/AsahProject.java, modules/dxp/apps/osb/osb-faro/osb-faro-mock-engine-client/src/main/java/com/liferay/osb/faro/mock/engine/client/internal/MockContactsEngineClientImpl.java, modules/dxp/apps/osb/osb-faro/osb-faro-service/src/main/java/com/liferay/osb/faro/model/impl/FaroProjectImpl.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/controller/main/ProjectController.java, modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/messaging/UpdateFaroProjectSubscriptionsMessageListener.java
Jira ticket: https://liferay.atlassian.net/browse/LPD-65804
=> LPD-65804 | faro-v4.14.x
